name: CI

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.11, 3.12]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "poetry"

            #- name: Install Poetry
            #  uses: snok/install-poetry@v1
            #  with:
            #      poetry-version: "1.6.1"

            #- name: Install dependencies
            #  run: poetry install --no-root

            #- name: Run taiga-stats
            #  run: |
            #      poetry run taiga-stats -v
            #      poetry run taiga-stats -h

            #- name: Lint and format
            #  #run: |
            #  #poetry run pylint taiga_stats/
            #  #poetry run black --check .
            #  run: |
            #      poetry run ruff check
            #      poetry run ruff format
